language: csharp

solution: Icarus.sln

mono:
  - latest

install:
  - nuget restore Icarus.sln

script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5" /p:DebugSymbols=False Icarus.sln