version: 1.0.{build}

os: Windows Server 2012

branches:
  except:
    - gh-pages

skip_tags: true

configuration: Release

build:
  project: ./Icarus.sln
  verbosity: minimal

before_build:
  - cmd: nuget restore ./Icarus.sln